// Generated by CoffeeScript 1.4.0
(function() {

  angular.module('myApp', ['myApp.filters', 'myApp.services', 'myApp.directives']).config([
    '$routeProvider', function($routeProvider) {
      return $routeProvider.when('/view1', {
        templateUrl: 'partials/partial1.html',
        controller: 'MyCtrl1'
      }).when('/view2', {
        templateUrl: 'partials/partial2.html',
        controller: 'MyCtrl2'
      }).otherwise({
        redirectTo: '/view1'
      });
    }
  ]);

}).call(this);
