// Generated by CoffeeScript 1.4.0
(function() {

  angular.module("myApp.directives", []).directive("appVersion", [
    "version", function(version) {
      return function(scope, elm, attrs) {
        return elm.text(version);
      };
    }
  ]);

}).call(this);
