// Generated by CoffeeScript 1.4.0
(function() {

  angular.module("myApp.filters", []).filter("interpolate", [
    "version", function(version) {
      return function(text) {
        return String(text).replace(/\%VERSION\%/g, version);
      };
    }
  ]);

}).call(this);
